apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-voucher-traveloka
  namespace: traveloka-app
  labels:
    app: fe-voucher-traveloka
spec:
  replicas: 1
  template:
    metadata:
      name: fe-voucher-traveloka
      labels:
        app: fe-voucher-traveloka
    spec:
      nodeSelector:
        ram: high
      containers:
        - name: fe-voucher-traveloka
          image: ghcr.io/whoant/vy2-fe-voucher-traveloka:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          envFrom:
            - secretRef:
                { name: secret.fe-voucher-traveloka }
            - configMapRef:
                { name: configmap.fe-voucher-traveloka }
      restartPolicy: Always
  selector:
    matchLabels:
      app: fe-voucher-traveloka
