version: '3.9'

services:
  vy02-fe-voucher-traveloka:
    container_name: vy02-fe-voucher-traveloka
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:80'
    environment:
      - NODE_ENV=production