apiVersion: v1
kind: Service
metadata:
  name: fe-voucher-traveloka
  namespace: traveloka-app
spec:
  selector:
    app: fe-voucher-traveloka
  ports:
    - port: 80
      targetPort: 81
      nodePort: 30003
  type: NodePort