name: Auto deploy develop ReactJS

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .env file
        run: |
          touch .env
          echo REACT_APP_END_POINT=${{secrets.REACT_APP_END_POINT}} > .env
          echo REACT_APP_PAYPAL_CLIENT_ID=${{secrets.REACT_APP_PAYPAL_CLIENT_ID}} >> .env
      - name: Stop container
        continue-on-error: true
        run: docker-compose down
      - name: Build image
        run: docker-compose build
      - name: Start container
        run: docker-compose up -d
