name: Auto deploy production ReactJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stop container
        continue-on-error: true
        run: docker-compose down
      - name: Create .env.docker file
        run: |
          touch .env.docker
          echo PORT=${{secrets.PORT}} > .env
      - name: Build image
        run: docker-compose build --no-cache
      - name: Start container
        run: docker-compose up -d