name: Cypress Tests with installation job

on:
  push:
    branches:
      - test

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.13.0-chrome95-ff94
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2 # use the explicit version number
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
