name: Auto deploy staging ReactJS

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stop container
        continue-on-error: true
        run: docker-compose down
      - name: Build image
        run: docker-compose build --no-cache
      - name: Start container
        run: docker-compose up -d